<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Y6sXCj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Y6sXCj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Y6sXCj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Y6sXCj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5Y6sXCj\App_KernelDevDebugContainer([
    'container.build_hash' => '5Y6sXCj',
    'container.build_id' => '7b9c9d16',
    'container.build_time' => 1685698521,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Y6sXCj');
