<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerABZYfKz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerABZYfKz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerABZYfKz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerABZYfKz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerABZYfKz\App_KernelDevDebugContainer([
    'container.build_hash' => 'ABZYfKz',
    'container.build_id' => 'cb76c302',
    'container.build_time' => 1684083399,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerABZYfKz');
