version: '3.8'

services:
    mysqldb:
      container_name: mysqlCTN
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: snowtricksDB
        #MYSQL_USER: beni
        #MYSQL_PASSWORD: mystere
      ports:
        - '4306:3306'
      volumes:
        - ./mysql:/var/lib/mysql

    adminer:
      image: adminer
      restart: on-failure
      ports:
        - '8082:8080'



    php:
      container_name: phpCTN
      build:
        context: ./php
      ports:
        - '9000:9000'
      volumes:
        - ./app:/var/www/snowtricksapp
      depends_on:
        - mysqldb


    nginx:
      container_name: nginxserverCTN
      image: nginx:stable-alpine
      ports:
        - '8080:80'
      volumes:
        - ./app:/var/www/snowtricksapp
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - mysqldb
