<?php

namespace ContainerUQIIAYf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PJAoQhmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pJAoQhm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pJAoQhm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.OtaMJSm', 'get_ServiceLocator_OtaMJSmService', true],
            'App\\Controller\\RegistrationController::resendVerif' => ['privates', '.service_locator.u85aek6', 'get_ServiceLocator_U85aek6Service', true],
            'App\\Controller\\RegistrationController::verifyUser' => ['privates', '.service_locator.2xuQBlm', 'get_ServiceLocator_2xuQBlmService', true],
            'App\\Controller\\SecurityController::forgottenPassword' => ['privates', '.service_locator.o4uQwLa', 'get_ServiceLocator_O4uQwLaService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::resetPass' => ['privates', '.service_locator.bLzGHAc', 'get_ServiceLocator_BLzGHAcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.OtaMJSm', 'get_ServiceLocator_OtaMJSmService', true],
            'App\\Controller\\RegistrationController:resendVerif' => ['privates', '.service_locator.u85aek6', 'get_ServiceLocator_U85aek6Service', true],
            'App\\Controller\\RegistrationController:verifyUser' => ['privates', '.service_locator.2xuQBlm', 'get_ServiceLocator_2xuQBlmService', true],
            'App\\Controller\\SecurityController:forgottenPassword' => ['privates', '.service_locator.o4uQwLa', 'get_ServiceLocator_O4uQwLaService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:resetPass' => ['privates', '.service_locator.bLzGHAc', 'get_ServiceLocator_BLzGHAcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::resendVerif' => '?',
            'App\\Controller\\RegistrationController::verifyUser' => '?',
            'App\\Controller\\SecurityController::forgottenPassword' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::resetPass' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:resendVerif' => '?',
            'App\\Controller\\RegistrationController:verifyUser' => '?',
            'App\\Controller\\SecurityController:forgottenPassword' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:resetPass' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
