<?php

namespace ContainerUQIIAYf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U85aek6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u85aek6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u85aek6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jwt' => ['privates', 'App\\Service\\JWTService', 'getJWTServiceService', true],
            'mail' => ['privates', 'App\\Service\\SendMailService', 'getSendMailServiceService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'jwt' => 'App\\Service\\JWTService',
            'mail' => 'App\\Service\\SendMailService',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
