<?php

namespace Container5Y6sXCj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTricksControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TricksController' shared autowired service.
     *
     * @return \App\Controller\TricksController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TricksController.php';

        $container->services['App\\Controller\\TricksController'] = $instance = new \App\Controller\TricksController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\TricksController', $container));

        return $instance;
    }
}
